name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - docker  # 在 `main` 分支 push 时触发
  pull_request:  # 可选，PR 时也可触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录到 GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.G_ACTOR }}
          password: ${{ secrets.G_TOKEN }}

      # 构建并推送镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/SJJ-dot/mysubconvert:latest  # 镜像标签为 "latest"
